### ISSUE TITLE
keys above F16 wont be recognized by 3rd party app

### ISSUE THREAD

**Issue by Richkan1** [ThioJoe/F-Key-Sender#1]
hey, thank you for this little program - very helpful :)
im using an azeron keypad which currently doesnt support binding F13-F24 by normal means.

your app works for F13-F16 but not for the rest of the function-keys.
i have tried both keypress methods, sendinput and keybd_event, but no dice.
would it be possible to implement another method to input those keys?

**Comment by ThioJoe** [comment]
It's likely a problem with the other app because this tool sends keys above F16 is the same as the F13-F16 keys

**Comment by Richkan1** [comment]
you are right.
i just tried binding F20 to the azeron app via logitech software, stream deck and another mouse software and it didnt accept it.
thx :)

**Comment by Richkan1** [comment]
you are right.
i just tried binding F20 to the azeron app via logitech software, stream deck and another mouse software and it didnt accept it.
thx :)
