### ISSUE TITLE
Add "App" key as a modifier

### ISSUE THREAD

**Issue by Gatorzgaming** [ThioJoe/F-Key-Sender#2]
Could be useful considering it's rarely used and now replaced by the copilot key. Personally I use it for my steam overlay in stuff, I think it deserves a spot considering how many keyboards don't include the key anymore.

**Comment by swimJim** [comment]
What is the app key? Is it like the Windows key?

**Comment by Gatorzgaming** [comment]
It's also known as the application key ![image](https://github.com/ThioJoe/F-Key-Sender/assets/73238668/a92920ca-369b-428b-a193-bf4446e0e41e)

**Comment by dxgldotorg** [comment]
Adding the Windows key could be useful too for non-Copilot keyboards as the Copilot key is just Win+Shift+F23.

**Comment by ThioJoe** [comment]
You could just use the Windows built-in on screen keyboard for the App key and really any other standard keys:

<img width="797" alt="image" src="https://github.com/ThioJoe/F-Key-Sender/assets/12518330/2d438f1b-c19d-4ff2-8457-3c0a1454130a">

That doesn't support the F13-F24 keys as far as I'm aware which is a reason I made this

**Comment by Gatorzgaming** [comment]
I forgot the onscreen keyboard even existed, it probably would work fine

**Comment by indigofairyx** [comment]
the "content menu key" isn't this the same as `Shift`+`F10` ?

this key and the hotkey behave the same on my keyboard right now.

**Comment by dxgldotorg** [comment]
> the "content menu key" isn't this the same as `Shift`+`F10` ?
> 
> this key and the hotkey behave the same on my keyboard right now.

It isn't actually; pressing the context menu key creates scancode 0x5D where Shift+F10 is 0x36 and 0x44.

**Comment by DevX-Cipher** [comment]
> You could just use the Windows built-in on screen keyboard for the App key and really any other standard keys:
> <img alt="image" width="797" src="https://private-user-images.githubusercontent.com/12518330/346314337-2d438f1b-c19d-4ff2-8457-3c0a1454130a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0ODM4OTgsIm5iZiI6MTcyMTQ4MzU5OCwicGF0aCI6Ii8xMjUxODMzMC8zNDYzMTQzMzctMmQ0MzhmMWItYzE5ZC00ZmYyLTg0NTctM2MwYTE0NTQxMzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEzNTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NjExZTQ4OWE1OGY3YjIxMGUwOTBkMzJjNzJiZmUyZDc4ZDdlYzRmMGM5YzkyZTdlN2ZhMTA5MDJlZTJkZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R6ILPhlBkQMAbCl24ZVoGGJQ8TehECHGoVhGtVeVqSA">
> 
> That doesn't support the F13-F24 keys as far as I'm aware which is a reason I made this

why not creat this into library so people can use this in there own project would be helpful maybe a nuget package as well

**Comment by UAVXP** [comment]
> > You could just use the Windows built-in on screen keyboard for the App key and really any other standard keys:
> > <img alt="image" width="797" src="https://private-user-images.githubusercontent.com/12518330/346314337-2d438f1b-c19d-4ff2-8457-3c0a1454130a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0ODM4OTgsIm5iZiI6MTcyMTQ4MzU5OCwicGF0aCI6Ii8xMjUxODMzMC8zNDYzMTQzMzctMmQ0MzhmMWItYzE5ZC00ZmYyLTg0NTctM2MwYTE0NTQxMzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEzNTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NjExZTQ4OWE1OGY3YjIxMGUwOTBkMzJjNzJiZmUyZDc4ZDdlYzRmMGM5YzkyZTdlN2ZhMTA5MDJlZTJkZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R6ILPhlBkQMAbCl24ZVoGGJQ8TehECHGoVhGtVeVqSA">
> > That doesn't support the F13-F24 keys as far as I'm aware which is a reason I made this
> 
> why not creat this into library so people can use this in there own project would be helpful maybe a nuget package as well

Create it yourself

**Comment by ThioJoe** [comment]
The latest version 1.1.0 now supports entering custom Virtual Key and Scan Codes, so you can have it do whatever keys you want 👍
