### ISSUE TITLE
How to build this?

### ISSUE THREAD

**Issue by Rustring** [ThioJoe/F-Key-Sender#3]
I want to compile this

**Comment by Ryckie** [comment]
You can simply download the .exe from the releases page.
https://github.com/ThioJoe/F-Key-Sender/releases

**Comment by ThioJoe** [comment]
> I want to compile this

Open the solution (.sln) file in Visual Studio 2022, it should be ready to compile (aka "Build") right away:

https://learn.microsoft.com/en-us/visualstudio/ide/building-and-cleaning-projects-and-solutions-in-visual-studio?view=vs-2022

**Comment by Rustring** [comment]
> You can simply download the .exe from the releases page. https://github.com/ThioJoe/F-Key-Sender/releases

I'm on Linux I just want to know how to generate a binary for Windows

**Comment by ThioJoe** [comment]
I don't know how to compile it on linux sorry. Maybe visual studio running with Wine?

**Comment by Rustring** [comment]
> I don't know how to compile it on linux sorry. Maybe visual studio running with Wine?

I wanted to know how to compile it on a Windows machine and no, running compilers inside wine is not possible,  you need a windows VM or machine to run a compiler

**Comment by megapro17** [comment]
use rider
